package uz.developers.university.config;

import com.google.common.collect.Sets;

import java.util.Set;

import static uz.developers.university.config.UserPermission.*;

public enum UserRole {

    //MINISTER, RECTOR, PRORECTOR, DEAN, CURATOR, STUDENT

    STUDENT(Sets.newHashSet(FACULTY_READ_ALL,FACULTY_READ_ONE,
            GROUP_READ_ALL,GROUP_READ_ONE,
            STUDENT_READ_ALL,STUDENT_READ_ONE,
            SUBJECT_READ_ALL,SUBJECT_READ_ONE)),


    CURATOR(Sets.newHashSet(ADDRESS_READ_ALL,ADDRESS_READ_ONE,
            FACULTY_READ_ALL,FACULTY_READ_ONE,
            GROUP_READ_ALL,GROUP_READ_ONE,GROUP_ADD,GROUP_EDIT,GROUP_DELETE,
            STUDENT_READ_ALL,STUDENT_READ_ONE,
            SUBJECT_READ_ALL,SUBJECT_READ_ONE)),


    DEAN(Sets.newHashSet(ADDRESS_READ_ALL,ADDRESS_READ_ONE,
            FACULTY_READ_ALL,FACULTY_READ_ONE,
            GROUP_READ_ALL,GROUP_READ_ONE,GROUP_ADD,GROUP_EDIT,GROUP_DELETE,
            STUDENT_READ_ALL,STUDENT_READ_ONE,
            SUBJECT_READ_ALL,SUBJECT_READ_ONE)),


    PRORECTOR(Sets.newHashSet(ADDRESS_READ_ALL,ADDRESS_READ_ONE,
            FACULTY_READ_ALL,FACULTY_READ_ONE,
            GROUP_READ_ALL,GROUP_READ_ONE,GROUP_ADD,GROUP_EDIT,GROUP_DELETE,
            STUDENT_READ_ALL,STUDENT_READ_ONE,
            SUBJECT_READ_ALL,SUBJECT_READ_ONE)),


    RECTOR(Sets.newHashSet(ADDRESS_READ_ALL,ADDRESS_READ_ONE,
            FACULTY_READ_ALL,FACULTY_READ_ONE,
            GROUP_READ_ALL,GROUP_READ_ONE,GROUP_ADD,GROUP_EDIT,GROUP_DELETE,
            STUDENT_READ_ALL,STUDENT_READ_ONE,
            SUBJECT_READ_ALL,SUBJECT_READ_ONE,
            UNIVERSITY_READ_ALL,UNIVERSITY_READ_ONE)),


    MINISTER(Sets.newHashSet(ADDRESS_READ_ALL,ADDRESS_READ_ONE,ADDRESS_ADD,ADDRESS_EDIT,ADDRESS_DELETE,
            FACULTY_READ_ALL,FACULTY_READ_ONE,FACULTY_ADD,FACULTY_EDIT,FACULTY_DELETE,
            GROUP_READ_ALL,GROUP_READ_ONE,GROUP_ADD,GROUP_EDIT,GROUP_DELETE,
            STUDENT_READ_ALL,STUDENT_READ_ONE,STUDENT_ADD,STUDENT_EDIT,STUDENT_DELETE,
            SUBJECT_READ_ALL,SUBJECT_READ_ONE,SUBJECT_ADD,SUBJECT_EDIT,SUBJECT_DELETE,
            UNIVERSITY_READ_ALL,UNIVERSITY_READ_ONE,UNIVERSITY_ADD,UNIVERSITY_EDIT,UNIVERSITY_DELETE));


    private final Set<UserPermission> permissions;

    UserRole(Set<UserPermission> permissions) {
        this.permissions = permissions;
    }

    public Set<UserPermission> getPermissions() {
        return permissions;
    }

}
